// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAGUJzRHEV0T-mC8PfKOiszvBM2lP5Hxg',
    appId: '1:452958690852:web:050f057804cda09f2b02b1',
    messagingSenderId: '452958690852',
    projectId: 'crytotracker-449a1',
    authDomain: 'crytotracker-449a1.firebaseapp.com',
    storageBucket: 'crytotracker-449a1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT_--X3UY8pT5WE0hkrgHt8-OSQvhFNVk',
    appId: '1:452958690852:android:2735c117800da5762b02b1',
    messagingSenderId: '452958690852',
    projectId: 'crytotracker-449a1',
    storageBucket: 'crytotracker-449a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLC2-Ad_tJNrIYNPxwSyuQg7vkC2j6LT0',
    appId: '1:452958690852:ios:5f980a9e70aafdff2b02b1',
    messagingSenderId: '452958690852',
    projectId: 'crytotracker-449a1',
    storageBucket: 'crytotracker-449a1.appspot.com',
    iosClientId: '452958690852-aa7g8hci1ssp4rtbf1cihjp3uolfgjo9.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLC2-Ad_tJNrIYNPxwSyuQg7vkC2j6LT0',
    appId: '1:452958690852:ios:2357d5fe51dfa8932b02b1',
    messagingSenderId: '452958690852',
    projectId: 'crytotracker-449a1',
    storageBucket: 'crytotracker-449a1.appspot.com',
    iosClientId: '452958690852-u63gheoq42rdv9qpft9mqk95m0atu7qe.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
